Change the source directory in absolute imports
pwr-TeamProject23/M2 pull request #28
Opened 2023-11-09 16:01 UTC by biegasj

2023-11-09 16:07 UTC, olgaszatkowska requested changes

2023-11-09 16:07 UTC, olgaszatkowska commented on backend/src/config.py
> +SCOPUS_API_KEY = environ.get("SCOPUS_API_KEY", "f49406af119d87c316da8c7fbd20137c")
?

2023-11-09 16:46 UTC, biegasj commented on backend/src/config.py
> +SCOPUS_API_KEY = environ.get("SCOPUS_API_KEY", "f49406af119d87c316da8c7fbd20137c")
A miało być tak pięknie...

2023-11-15 17:09 UTC, olgaszatkowska approved these changes

2023-11-15 17:09 UTC, merged